version: '3'
services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT}
        APP_DIR: ${APP_DIR}
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    container_name: redis-test
